In [1]:
a=3
print(a)
b=3.43
print (b)
c='esto es un ejemplo'
print (c)

#A continuación se imprime en pantalla el tipo de dato de cada variable
print(type(a))
print(type(b))
print(type(c))

3
3.43
esto es un ejemplo
<class 'int'>
<class 'float'>
<class 'str'>


In [2]:
num_a=3.14
num_b=int(num_a)
print(num_b)
print(type(num_b))

a_int=4
#Se convierte el número entero a string
a_str=str(a_int)
#Ahora se puede concatenar la variable con otra cadena de texto
print ("el número elegido es "+ a_str)
a_int = 2
#Se convierte el número a entero a flotante
a_float = float(a_int)
print(a_float)

3
<class 'int'>
el número elegido es 4
2.0


In [3]:
# Operaciones simples
a = 10+5 #Suma
b = a-6.16 #Resta
c = b*3 #Multiplicación
d = c/2 #División

#Se define la variable
a=10
#Se opera sobre el valor anterior de la misma
a=a+3
#Una manera más programática de escribir lo mismo:
a+=3
a*=3

a=5%2
print (a)
b=4%2
print(b)

1
0


In [5]:
#Operaciones con textos (string)

str_a="¡Hola"
str_b="Mundo!"
str_c= str_a+str_b
print(str_c)
# Otra manera de realizar lo mismo, sin crear una variable:
print(str_a+str_b)

a="Cantidad: "
b=6
print(a+str(b))

a="Juan"
print(a+" tiene "+str(3)+" hijos")

a=input("Ingrese su nombre: ")
print ("Usted ingresó: "+a)

a=int(input("Ingrese un número: "))
b=a+2
print ("El resultado de "+ str(a)+"+2 es= "+str(b))

¡HolaMundo!
¡HolaMundo!
Cantidad: 6
Juan tiene 3 hijos
Usted ingresó: AEG
El resultado de 39+2 es= 41


In [6]:
a= "Hola"
print (a)
print("Mundo")

str_a="Hola"
str_b="Mundo"
str_c=str_a+str_b
print(str_c)
#Concatenación a traves de comas 
a="Carlos"
b="34"
print("Su nombre es ",a,"y tiene",b,"años")

a="Carlos"
b="34"
print("Su nombre es {a} y tiene {b} años")

a=input("Ingrese su edad: ")
print("La edad ingresada fue: "+a)

Hola
Mundo
HolaMundo
Su nombre es  Carlos y tiene 34 años
Su nombre es {a} y tiene {b} años
La edad ingresada fue: 39


In [8]:
#FUNCIONES
def funcion_ejemplo (parametro1,parametro2):
    variable_ejemplo = parametro1 + parametro2
    print(variable_ejemplo)

#Se define la función 
def suma(num_a,num_b):
    resultado= num_a + num_b
    print(f"El resultado de {num_a} + {num_b} es {resultado}")
    
#Habiendo definido la función, aquó comienza el script:
a=3
b=5
c=2
#Se invoca a la función creada previamente, pasando como 
#parámetro las variables de interés
suma(a,b)
suma(b,c)

#Se define la función 
def suma(num_a,num_b):
    resultado= num_a + num_b
    return resultado
    
#Habiendo definido la función, aquó comienza el script:
a=3
b=5

#Se invoca a la función creada previamente, pasando como 
#parámetro las variables de interés.
#Se almacena el resultado de la función en la variable "res"
res=suma(a,b)
print(f"El resultado es {a} + {b} es {res}")

El resultado de 3 + 5 es 8
El resultado de 5 + 2 es 7
El resultado es 3 + 5 es 8


In [10]:
#Operaciones con Numpy
import numpy as np

x=[2,3,4,5]
nums = np.array(x)

#Vector multiplicado
print(nums*2)

#Vector normalizado
print(nums/(np.max(nums)))

nums=np.array([[2,2,3],[8,11,9]])
print(nums)

[ 4  6  8 10]
[0.4 0.6 0.8 1. ]
[[ 2  2  3]
 [ 8 11  9]]


In [12]:
import pandas as pd
datos={"Películas o Series":["Titanic","Harry Potter", "Breaking Bad", "Lutter"], 
       "Lanzamientos":["1999","2005","2010","2020"], "Puntaje de los Usuarios":[80,90,92,95]}
df=pd.DataFrame(datos)
# print(df)

género=["Drama", "Cs.Ficción", "Acción", "Comedia"]
df1=pd.DataFrame(datos, index=género)
# print(df1)

import pandas as pd
datos={"título":["BreakingBad","Game of Thrones",
                 "The Office","Stranger Things","Friend"],
"Año de Estreno":[2008,2011,2005,2016,1994],
"Género":["Drama", "Fantasía","Comedia","Ciencia Ficción","Comedia"]}
df=pd.DataFrame(datos)
print(df)

            título  Año de Estreno           Género
0      BreakingBad            2008            Drama
1  Game of Thrones            2011         Fantasía
2       The Office            2005          Comedia
3  Stranger Things            2016  Ciencia Ficción
4           Friend            1994          Comedia


In [13]:
a=float(10+3)
print(type(a),a)

b=int(10/3)
print(type(b),b)

c=float(5*2)
print(type(c),c)

<class 'float'> 13.0
<class 'int'> 3
<class 'float'> 10.0


In [14]:
# 1. Crear Diccionario con datos personales.
dp={'Nombre':'Juan','Apellido':'Perez','Edad':34}
print(dp)

# 2. Pedir al Usuario la Nacionalidad.
Nacionalidad=input('indique su nacionalidad: ')
print(Nacionalidad)
dp['Nacionalidad']= Nacionalidad
print(dp)

# 3. Texto descriptivo.
print(f"El nombre es {dp['Nombre']} {dp['Apellido']}, tiene {dp['Edad']} años y es de nacionalidad {dp['Nacionalidad']}.")



{'Nombre': 'Juan', 'Apellido': 'Perez', 'Edad': 34}
Argentina
{'Nombre': 'Juan', 'Apellido': 'Perez', 'Edad': 34, 'Nacionalidad': 'Argentina'}
El nombre es Juan Perez, tiene 34 años y es de nacionalidad Argentina.


In [15]:
registro= {"nombre":"Juan","edad":54}
registro["país"]="Argentina"
print(registro)

print(f"su nombre es{registro['nombre']},tiene{registro['edad']}años y vive en {registro['país']}")

{'nombre': 'Juan', 'edad': 54, 'país': 'Argentina'}
su nombre esJuan,tiene54años y vive en Argentina


In [16]:
# Divisible 3 = Fizz
# Divisible 5 = Buzz
# Divisible por 3 y 5 = FizzBuzz
# No Divisible por 3 o 5 = se imprime el número

for num in range(1,21):
    if num%3 == 0 and num%5 ==0:
        print(f"Fizz Buzz")
    elif num%3 == 0:
        print(f"Fizz")
    elif num%5 ==0:
         print(f"Buzz")
    else:
          print(num)  

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
Fizz Buzz
16
17
Fizz
19
Buzz


**by Analía Elizabeth Gomory**

* ae.gomory@gmail.com

* http://www.linkedin.com/in/elizabeth-gomory-9240b1217

* https://ae-gomory.itch.io

* https://github.com/ElizabethGomory

* https://www.credly.com/users/analia-gomory

* https://orcid.org/0009-0003-0498-7658